version: '3.8'

services:
  speedynote:
    build: .
    container_name: speedynote-app
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=info
      - PORT=3000
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.speedynote.rule=Host(`speedynote.local`)"
      - "traefik.http.services.speedynote.loadbalancer.server.port=3000"

  # 可选：数据库服务（用于笔记存储）
  database:
    image: postgres:15-alpine
    container_name: speedynote-db
    environment:
      - POSTGRES_DB=speedynote
      - POSTGRES_USER=speedynote
      - POSTGRES_PASSWORD=password123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U speedynote"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:

networks:
  default:
    name: speedynote-network